
// A, AAAA, CNAME records
export const subdomainsRecords: String[] = [
    'admin',
    'analytics',
    'api',
    'app',
    'apps',
    'assets',
    'beta',
    'blog',
    'bounces',
    'cdn',
    'cloud',
    'cpanel',
    'dashboard',
    'dash',
    'data',
    'demo',
    'dev',
    'docs',
    'edge',
    'email',
    'files',
    'ftp',
    'help',
    'imap',
    'labs',
    'mail',
    'mx',
    'shop',
    'store',
    'support',
    'test',
    'testing',
    'www',
    'webmail',
];

// common found TXT records
export const txtRecords: String[] = [
    '_amazonses',
    '_dmarc',
    '_domainkey',
    'default._domainkey',
    'google._domainkey',
    'mail._domainkey',
    'default._bimi',
];
